package com.altaf.web2apk;
import android.app.*; import android.os.*; import android.content.*; import android.net.*; import android.view.*; import android.webkit.*; import android.widget.*; import android.graphics.Color; import android.graphics.Bitmap; import android.provider.MediaStore;
public class MainActivity extends Activity {
 static final String HOME="__WEB2APK_URL__", BG="__SPLASH_BG__", ACCENT="__ACCENT__"; static final int SPLASH_MS=__SPLASH_MS__; WebView web; ProgressBar progress; FrameLayout root; TextView splash; ValueCallback<Uri[]> chooser; final int PICK=71;
 @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.parseColor(ACCENT));getWindow().setNavigationBarColor(Color.parseColor(ACCENT));root=new FrameLayout(this);web=new WebView(this);progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);root.addView(web,new FrameLayout.LayoutParams(-1,-1));FrameLayout.LayoutParams pp=new FrameLayout.LayoutParams(-1,6);pp.gravity=Gravity.TOP;root.addView(progress,pp);splash=new TextView(this);splash.setText("__APP_NAME_JAVA__");splash.setTextSize(28);splash.setTextColor(Color.WHITE);splash.setGravity(Gravity.CENTER);splash.setBackgroundColor(Color.parseColor(BG));root.addView(splash,new FrameLayout.LayoutParams(-1,-1));setContentView(root);
 WebSettings s=web.getSettings();s.setJavaScriptEnabled(__JS_ENABLED__);s.setDomStorageEnabled(true);s.setDatabaseEnabled(true);s.setLoadsImagesAutomatically(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);s.setCacheMode(WebSettings.LOAD_DEFAULT);s.setMediaPlaybackRequiresUserGesture(false);s.setBuiltInZoomControls(__ZOOM_ENABLED__);s.setDisplayZoomControls(false);s.setSupportZoom(__ZOOM_ENABLED__);s.setAllowFileAccess(true);CookieManager.getInstance().setAcceptCookie(true);CookieManager.getInstance().setAcceptThirdPartyCookies(web,true);
 web.setDownloadListener((url,ua,cd,mime,len)->{try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){}});
 web.setWebChromeClient(new WebChromeClient(){public void onProgressChanged(WebView v,int p){progress.setProgress(p);progress.setVisibility(p>=100?View.GONE:View.VISIBLE);} @Override public boolean onShowFileChooser(WebView v,ValueCallback<Uri[]> cb,FileChooserParams fp){if(chooser!=null)chooser.onReceiveValue(null);chooser=cb;try{startActivityForResult(fp.createIntent(),PICK);}catch(Exception e){chooser=null;return false;}return true;}});
 web.setWebViewClient(new WebViewClient(){@Override public boolean shouldOverrideUrlLoading(WebView v,WebResourceRequest r){Uri u=r.getUrl();String q=u.getScheme();if("http".equals(q)||"https".equals(q)){if(__EXTERNAL_LINKS__ && !sameHost(u)){startActivity(new Intent(Intent.ACTION_VIEW,u));return true;}return false;}try{startActivity(new Intent(Intent.ACTION_VIEW,u));}catch(Exception e){}return true;} @Override public void onReceivedError(WebView v,WebResourceRequest r,WebResourceError e){if(r.isForMainFrame())showError("Internet ya website load nahi hui.");}});
 web.loadUrl(HOME);new Handler(Looper.getMainLooper()).postDelayed(()->{splash.animate().alpha(0f).setDuration(250).withEndAction(()->root.removeView(splash)).start();},SPLASH_MS);}
 boolean sameHost(Uri u){String a=u.getHost(),b=Uri.parse(HOME).getHost();return a!=null&&a.equalsIgnoreCase(b);}
 void showError(String m){String h="<html><meta name='viewport' content='width=device-width'><body style='font-family:sans-serif;text-align:center;padding:60px 24px'><h2>You're offline</h2><p>"+m+"</p><button style='padding:12px 24px' onclick='location.href=\""+HOME+"\"'>Retry</button></body></html>";web.loadDataWithBaseURL(HOME,h,"text/html","UTF-8",null);}
 @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&chooser!=null){chooser.onReceiveValue(WebChromeClient.FileChooserParams.parseResult(c,d));chooser=null;}}
 @Override public void onBackPressed(){if(web.canGoBack())web.goBack();else super.onBackPressed();}
}